export const bucketName = 'jobscanner-test'
export const bucketRegion = 'us-east-2'
export const identityPoolId = 'us-east-2:24f7c99e-aaae-4e9c-847a-0aea505dbddb'
export const bucketPath = 'resume_upload'
export const jobFunctionAPIBase = 'https://hg7anlpup9.execute-api.us-east-2.amazonaws.com/Prod'
